### PR TITLE
updated OutputParametricCachedSelector definition

### PR DESCRIPTION
**Pull request by Dante-101**
Fixes https://github.com/toomuchdesign/re-reselect/issues/15

### CODE REVIEW

**Comment by toomuchdesign** [comment]
Hi @Dante-101, thanks for the PR!
Now that you point out out, I caught the error, too.

BTW, I see in your PR that you replaced `ParametricSelector` with `OutputParametricCachedSelector`. Did you mean `OutputParametricSelector`, right?

Cheers!

**Comment by toomuchdesign** [comment]
@xsburg, sorry to bother you again!
Would you like to double check this PR? ;)

**Comment by xsburg** [comment]
@Dante-101, thanks for pointing out the mistake.
@toomuchdesign, @Dante-101, I think it's definitely a way forward, I added a few tests and updated OutputCachedSelector as well in #18. Also, I think we don't need to use `any`, since we could just use parameter `C`.

**Comment by toomuchdesign** [comment]
So good! Thank you all. I'll add a few more TS tests to reinforce the new additions.

As a last TS detail, I think `OutputParametricCachedSelector` should ensure that `getMatchingSelector` and `removeMatchingSelector` are called with at least `state` and `props` as args. That is to say they expose the same interface as `ParametricResolver`. If that's ok, I'll add it on top of the last PR. 

Current:
```
export type OutputParametricCachedSelector<S, P, R, C> = (resolver: ParametricResolver<S, P>) => OutputParametricSelector<S, P, R, C> & {
  getMatchingSelector: (state: S, ...args: any[]) => OutputParametricSelector<S, P, R, C>;
  removeMatchingSelector: (state: S, ...args: any[]) => void;
```

Proposed change:
```
export type OutputParametricCachedSelector<S, P, R, C> = (resolver: ParametricResolver<S, P>) => OutputParametricSelector<S, P, R, C> & {
  getMatchingSelector: (state: S, props:P, ...args: any[]) => OutputParametricSelector<S, P, R, C>;
  removeMatchingSelector: (state: S, props:P, ...args: any[]) => void;
```

**Comment by Dante-101** [comment]
My bad. It should be `OutputParametricSelector`.

As far as I understand, we can't use the parameter `C` in this case because the `resultFunc` of each selector has a different type. `C` is for the Selector returned by re-reselect.

So either we take a new list of generic function definitions for each selector or we use any.

**Comment by xsburg** [comment]
@toomuchdesign, agreed, that's the missing piece!
@Dante-101, `resultFunc` is actually the same, what we do in `getMatchingSelector` is just retrieve the reselect function responsible for a particular key:
```
// in constructor
cache[cacheKey] = createSelectorInstance(...funcs);
// ...
// in getMatchingSelector
return cache[cacheKey];
```

**Comment by Dante-101** [comment]
Yes. That is correct. My bad. I was thinking in some other direction.

**Pull request merged**
