### PR TITLE
upgrade reselect and fix tests

### PR DESCRIPTION
**Pull request by veksa**
### What kind of change does this PR introduce? _(Bug fix, feature, docs update, ...)_

Upgrade reselect package to v5.0.1
Fix failed tests after upgrade
Upgrade jest to cover new mock

### Does this PR introduce a breaking change? _(What changes might users need to make in their application due to this PR?)_

no

### Please check if the PR fulfills these requirements:

- [x] Tests for the changes have been added
- [ ] Docs have been added / updated

### CODE REVIEW

**Comment by toomuchdesign** [comment]
Hi @veksa, thanks for your PR.

`reselect` v5 seems quite a relevant breaking change, would it make sense releasing a new `re-reselect` major providing support for `reselect` v5+ only?

**Comment by veksa** [comment]
I guess yes, should i change peerDependencies version to ">5.0.0"?

**Comment by toomuchdesign** [comment]
I will, I need to find time to review your pr and possibly do some maintenance. I wonder whether we should review types based on the new reselect implementation. Or possibly switch to TS. I haven't touched redux application for a while.

I read `reselect` v5 implements some caching logic now, do you know which use case `reselect` cannot cover yet compared to `re-reselect`?

**Comment by veksa** [comment]
make some comparison between caches:

image

It looks like `flat-object` is significantly better than `WeakMap` or `autotrackWeakMap`.

`WeakMap` or `autotrackWeakMap` is better only in that there is no need to manually manage the `keySelector`.

The types in Reselect have undergone significant changes; I can migrate the project to TypeScript, and it's possible that type handling will be simplified.

**Comment by toomuchdesign** [comment]
In order to have a better understanding of the undergoing changes I opened this PR using yours as a blueprint. Sorry for this but It was the only way to try and make this update happen.

https://github.com/toomuchdesign/re-reselect/pull/214

Porting the project to TS could be useful but probably time consuming, too. Let's think about it.

**Pull request closed without merging**
