### PR TITLE
Upgrade to Babel 7

### PR DESCRIPTION
**Pull request by Andarist**
### What kind of change does this PR introduce? _(Bug fix, feature, docs update, ...)_

Upgrade to Babel 7. The library should weigh a little bit less now as babel@7 produces more terse code.

### CODE REVIEW

**Comment by toomuchdesign** [comment]
Hi @Andarist,
thank you for your PR!

I opened a [dedicated branch](https://github.com/toomuchdesign/re-reselect/tree/babel-7) for upgrading to babel 7.

Since it's my first time with babel 7, I have a couple of question you might be able to answer. :)

Is `@babel/preset-env` the right tool for libraries, too?
I value the ease of configuration, of course :), but from my maintainer's perspective I wander if it's the right approach, since I will always want to produce 100% ES5 transpiled code. Is `@babel/preset-env` currently considered the way to go in any case?

As for the transpiled output, the minified artefacts weight about 500 byte more then `babel v6`. It's mainly due to different strategies in ES6 classes transpilation.

BTW not a big deal if users have working tree-shaking.

Thank's for your time.
Greetings!

**Comment by Andarist** [comment]
> I value the ease of configuration, of course :), but from my maintainer's perspective I wander if it's the right approach, since I will always want to produce 100% ES5 transpiled code. Is @babel/preset-env currently considered the way to go in any case?

Yeah, it's the way to go. It's nice as it encapsulates all the standardized plugins in it. Until you try to configure it to compile to the features supported in some browsers it transforms your code down to es5. It might try to find browserlist files or browserlist field in package.json to check if you have it configured, if you are worried about accidentally adding them in the future for other use cases/tools you might want to add `forceAllTransforms: true` option, https://babeljs.io/docs/en/babel-preset-env#forcealltransforms

> As for the transpiled output, the minified artefacts weight about 500 byte more then babel v6. It's mainly due to different strategies in ES6 classes transpilation.

Interesting, in most cases it should yield slightly better results (in favour of babel@7). I'll recheck babel@6 and babel@7 outputs to see if I can find any reason for the observed results.

**Comment by Andarist** [comment]
Testing with
```sh
npx terser -cm --toplevel es/index.js | gzip -c | wc -c
```
- babel@6 - 1086
- babel@7 - 1021

So actually slightly better when minified & gzipped.

**Comment by Andarist** [comment]
I've tested babel@7 on my branch, but it seems that you have changed the configs slightly - the increased size is caused by not using the loose mode, which is used on master. Any reason why you have removed the loose flag?

**Comment by toomuchdesign** [comment]
Actually no good reasons :). I just lost the flag while upgrading
`.babelrc` file!

I didn't realize that old es-2015 preset and babel-env expose the same
`loose` flag.

I'll try again tomorrow with the proper configuration.

Thanks for your detailed analysis. I'll keep you updated!

Cheers!

**Comment by toomuchdesign** [comment]
Quick update:
Babel 6 and Babel 7 generate now the same output except for `classCallCheck` helper which [Babel 7 doesn't include anymore on `loose` mode](https://babeljs.io/blog/2018/08/27/7.0.0#output-options). 👍 

Not sure if I should consider it a breaking change.

**Comment by Andarist** [comment]
I wouldnt consider this a breaking change - especially that the behaviour is loosened up and not stricter. Either way it shouldnt change anything for anyone using the library correctly.

Babel 7 also produces shorter prototype assignments by caching prototype in a variable

**Comment by toomuchdesign** [comment]
That was my first thought, too.
Great, now that the first step is done, I'll consider moving my other thing to Babel 7.

Thank you so much for your support!

**Pull request merged**
